name: Publish packages

on:
  workflow_dispatch:

jobs:
 publish:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
   steps:
     - uses: actions/checkout@v7

     - uses: pnpm/action-setup@v6
       with:
         version: 11.8.0

     - uses: actions/setup-node@v6
       with:
         node-version: 24
         registry-url: "https://npm.pkg.github.com"
         scope: "@max13h"

     - run: pnpm install --frozen-lockfile

     - run: pnpm --filter '@max13h/*' publish --access public --no-git-checks
       env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
